### ISSUE TITLE
A walkthrough?

### ISSUE THREAD

**Issue by idkjs** [jchavarri/rebind#3]
This is a super idea. Thanks for sharing it. Let me first say that I know this is totally experimental. So just as an exercise to learn. 

I have this code that I want to create a binding for to use [aws-appsync](https://github.com/awslabs/aws-mobile-appsync-sdk-js):

```
 const client = new AWSAppSyncClient({
   url: graphqlEndpoint,
   region: region,
   auth: {
     type: authenticationType,
     apiKey: apiKey
   }
 });
```
Running `rebind testRebind.js | refmt --parse binary --print re` gets you nothing just b/c this is experimental.

So you take out the `new` just to mess around.
```
 const client = AWSAppSyncClient({
   url: graphqlEndpoint,
   region: region,
   auth: {
     type: authenticationType,
     apiKey: apiKey
   }
 });
```

rebind output:

```s
type graphqlEndpoint;

type region;

type authenticationType;

type apiKey;

type aWSAppSyncClientParam;

type aWSAppSyncClientParam;

type aWSAppSyncClient;

[@bs.module] external graphqlEndpoint : graphqlEndpoint = "";

[@bs.module] external region : region = "";

[@bs.module] external authenticationType : authenticationType = "";

[@bs.module] external apiKey : apiKey = "";

[@bs.obj]
external makeAWSAppSyncClientParam :
  (~apiKey: apiKey, ~type: authenticationType, unit) => aWSAppSyncClientParam =
  "";

[@bs.module]
external aWSAppSyncClient : aWSAppSyncClientParam => aWSAppSyncClient = "";

```

Ok. So now we have something. We can add the `new` back after. Remember, best case!

Cleaning this up we take out the double `type aWSAppSyncClientParam;`. Also the params are just strings so lets remove the `[@bs.module]`'s for each param. Also `type` is a reserved keyword so we change it to `_type`.

These are the params:
```
      "graphqlEndpoint": "https://someendpoint.appsync-api.eu-west-1.amazonaws.com/graphql",
      "region": "eu-west-1",
      "authenticationType": "API_KEY",
      "apiKey": "da2-somerandomekeyalfasdf"
```
So we end up with:
```
// AWS.re
module AppSync = {
  type graphqlEndpoint = string;
  type region = string;
  type authenticationType = string;
  type apiKey = string;
  type aWSAppSyncClientParam;
  type aWSAppSyncClient;
  /* [@bs.module] external graphqlEndpoint : graphqlEndpoint = "";
     [@bs.module] external region : region = "";
     [@bs.module] external authenticationType : authenticationType = "";
     [@bs.module] external apiKey : apiKey = ""; */
  [@bs.obj]
  external makeAWSAppSyncClientParam :
    (
      ~apiKey: apiKey,
      ~url: graphqlEndpoint,
      ~region: region,
      ~_type: authenticationType,
      unit
    ) =>
    aWSAppSyncClientParam =
    "";
  [@bs.module "aws-appsync"] [@bs.new]
  external aWSAppSyncClient : aWSAppSyncClientParam => aWSAppSyncClient = "";
};
```

To create a client, then, we would do this:

```
//Client.re
module Client = AWS.AppSync;

let options =
  Client.makeAWSAppSyncClientParam(
    ~url=
      "https://someendpoint.appsync-api.eu-west-1.amazonaws.com/graphql",
    ~region="eu-west-1",
    ~_type="API_KEY",
    ~apiKey="da2-somerandomekeyalfasdf"
    (),
  );

let client = Client.aWSAppSyncClient(options);
```

Generally, is this workflow going in the right direction?

Thank you, sir.

**Comment by jchavarri** [comment]
Hey!

I think you're totally in the right direction. Some of the `rebind` issues you point out are part of the things that I want to fix at some point, like fix duplicates and add support for `new`.

Other things like the types not being strings and instead being abstract types will never be fixed. `rebind` will never have all the information (by design), it's just kind of a tool to help get us started, not write all the bindings.

The only thing that I could point out from your example is the lower case in `aWSAppSyncClient`. Just defining the "native" name between quotes should fix it:

```reason
[@bs.module "aws-appsync"] [@bs.new]
  external aWSAppSyncClient : aWSAppSyncClientParam => aWSAppSyncClient = "AWSAppSyncClient";
```

**Comment by idkjs** [comment]
Thanks for the feedback, boss. I dont mind assisting on this if your dont mind leading. Let me know. Peace to you.
